# Generated by Django 5.0.6 on 2024-06-17 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField(db_index=True, unique=True, verbose_name='Номер счета')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('date_birth', models.DateField(verbose_name='Дата рождения')),
                ('inn', models.IntegerField(db_index=True, unique=True, verbose_name='ИНН')),
                ('status', models.CharField(choices=[('in_progress', 'В работе'), ('not_in_work', 'Не в работе'), ('refusal', 'Отказ'), ('deal_closed', 'Сделка закрыта')], default='not_in_work', max_length=255, verbose_name='Статус')),
                ('manager', models.ForeignKey(default='users.CustomUser', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственное лицо')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
